export const PINS_LIST_REQUEST = "PINS_LIST_REQUEST";
export const PINS_LIST_SUCCESS = "PINS_LIST_SUCCESS";
export const PINS_LIST_FAIL = "PINS_LIST_FAIL";

export const PINS_CREATE_REQUEST = "PINS_CREATE_REQUEST";
export const PINS_CREATE_SUCCESS = "PINS_CREATE_SUCCESS";
export const PINS_CREATE_FAIL = "PINS_CREATE_FAIL";

export const PINS_UPDATE_REQUEST = "PINS_UPDATE_REQUEST";
export const PINS_UPDATE_SUCCESS = "PINS_UPDATE_SUCCESS";
export const PINS_UPDATE_FAIL = "PINS_UPDATE_FAIL";

export const PINS_DELETE_REQUEST = "PINS_DELETE_REQUEST";
export const PINS_DELETE_SUCCESS = "PINS_DELETE_SUCCESS";
export const PINS_DELETE_FAIL = "PINS_DELETE_FAIL";
