export const ALL_PINS_REQUEST = "ALL_PINS_REQUEST";
export const ALL_PINS_SUCCESS = "ALL_PINS_SUCCESS";
export const ALL_PINS_FAIL = "ALL_PINS_FAIL";

export const ADMIN_PINS_REQUEST = "ADMIN_PINS_REQUEST";
export const ADMIN_PINS_SUCCESS = "ADMIN_PINS_SUCCESS";
export const ADMIN_PINS_FAIL = "ADMIN_PINS_FAIL";

export const NEW_PINS_REQUEST = "NEW_PINS_REQUEST";
export const NEW_PINS_SUCCESS = "NEW_PINS_SUCCESS";
export const NEW_PINS_RESET = "NEW_PINS_RESET";
export const NEW_PINS_FAIL = "NEW_PINS_FAIL";

export const UPDATE_PINS_REQUEST = "UPDATE_PINS_REQUEST";
export const UPDATE_PINS_SUCCESS = "UPDATE_PINS_SUCCESS";
export const UPDATE_PINS_RESET = "UPDATE_PINS_RESET";
export const UPDATE_PINS_FAIL = "UPDATE_PINS_FAIL";

export const DELETE_PINS_REQUEST = "DELETE_PINS_REQUEST";
export const DELETE_PINS_SUCCESS = "DELETE_PINS_SUCCESS";
export const DELETE_PINS_RESET = "DELETE_PINS_RESET";
export const DELETE_PINS_FAIL = "DELETE_PINS_FAIL";

export const PINS_DETAILS_REQUEST = "PINS_DETAILS_REQUEST";
export const PINS_DETAILS_SUCCESS = "PINS_DETAILS_SUCCESS";
export const PINS_DETAILS_FAIL = "PINS_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
